<?php

declare(strict_types=1);

namespace Zain\LaravelDoctrine\Algolia;

use LaravelDoctrine\ORM\DoctrineServiceProvider;
use Orchestra\Testbench\TestCase as OrchestraTestCase;
use Zain\LaravelDoctrine\Algolia\Fixtures\Entities\Post;
use Zain\LaravelDoctrine\Algolia\Fixtures\Normalizers\CommentNormalizer;
use Zain\LaravelDoctrine\Algolia\Fixtures\Normalizers\ImageNormalizer;
use Zain\LaravelDoctrine\Algolia\Fixtures\Normalizers\PostNormalizer;

class TestCase extends OrchestraTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
            DoctrineServiceProvider::class,
            AlgoliaServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub
    }

    protected function configureCommentNormalizer($app): void
    {
        $app->config->set('algolia.search.normalizers', [CommentNormalizer::class]);
    }

    protected function configureImageNormalizer($app): void
    {
        $app->config->set('algolia.search.normalizers', [ImageNormalizer::class]);
    }

    protected function configurePostEntityIndex($app): void
    {
        $indices = $app->config->get('algolia.search.indices');
        $indices['post'] = [
            'class' => Post::class,
            'normalizer' => PostNormalizer::class,
        ];
        $app->config->set('algolia.search.indices', $indices);
    }
}
